---
- name: Check nginx app health and run diagnostics if unavailable
  hosts: all
  execution_strategy: parallel
  sources:
    - name: Listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.normalize_keys:
  rules:
###############################################################################################
############################ RUN THE DIAGNOSTICS ##############################################

    - name: Create incident on ServiceNow and run diagnostics
      condition: event.payload.commonLabels.alertname == "systemd failed service"
      action:
        run_job_template:
          name: NGINX_DIAGNOSTICS
          organization: ai_ops_mcp_demo
          post_events: true
          job_args:
            extra_vars:
              short_description: "Systemd failure on {{ event.payload.commonLabels.instance }}"
              description: "Systemd failure on {{ event.payload.commonLabels.instance }} - EDA will run diagnostics"
              impact: 1
              urgency: 1
              target_host: "{{ event.payload.commonLabels.instance }}"

###############################################################################################
#### RULES BELOW WILL BE TRIGGERED ON SECOND RUN (POST_EVENTS:TRUE) IF ANY CONDITIONS MATCH ###

    # Working remediation
    - name: Remediate TLS certificate issue
      condition: >
          event.diagnostics is defined and
          event.diagnostics.nginx_config_error is match(".*cannot load certificate key.*", ignorecase=true)
      action:
        run_workflow_template:
          name: TLS_ISSUE_AUTO_REMEDIATE
          organization: ai_ops_mcp_demo
          job_args:
            extra_vars:
              incident_sys_id: "{{ event.incident_sys_id }}"
              target_host: "{{ event.target_host }}"
              close_notes: | # on Success
                ########### EDA REMEDIATION STATUS UPDATE - SUCCESS #############

                A TLS certificate verification failure was detected. This may be caused by an
                expired certificate, a self-signed certificate that is not trusted, a missing
                root or intermediate CA, or a mismatch between the certificate and its private key.

                EDA has replaced the cert/key pair and remediated successfully.
              work_notes: | # on Failure
                ########## EDA REMEDIATION STATUS UPDATE - FAIL ##############

                A TLS certificate verification failure was detected. This may be caused by an
                expired certificate, a self-signed certificate that is not trusted, a missing
                root or intermediate CA, or a mismatch between the certificate and its private key.
                Please verify the certificate chain and ensure the correct key is configured.

                EDA has not been successful in the attempted remediation. Please investigate.

                The diagnostics report below may be of some assistance.


    # Remediation will fail
    - name: Remediate nginx config error
      condition: >
          event.diagnostics is defined and
          event.diagnostics.nginx_config_error is match(".*unknown directive.*", ignorecase=true)
      action:
        run_workflow_template:
          name: WORKFLOW-ATTEMPT_AUTO_REMEDIATION
          organization: ai_ops_mcp_demo
          job_args:
            extra_vars:
              incident_sys_id: "{{ event.incident_sys_id }}"
              target_host: "{{ event.target_host }}"
              close_notes: | # on Success
                ############# EDA REMEDIATION STATUS UPDATE - SUCCESS ##############

                The nginx configuration file contains an unknown directive, which indicates
                a potential typo or unsupported instruction.

                EDA has successfully remediated.
              work_notes: | # on Failure
                ############# EDA REMEDIATION STATUS UPDATE - FAIL ####################

                The nginx configuration file contains an unknown directive, which indicates
                a potential typo or unsupported instruction. Please verify the config for
                syntax issues or misconfigured modules.

                EDA has not been successful in the attempted remediation. Please investigate.

                The diagnostics report below may be of some assistance.

